language: node_js
node_js: 6
dist: xenial
services:
- docker
cache:
  npm: true
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

before_install:
- docker pull malept/electron-forge-container:latest

script:
- sudo docker run --privileged --interactive --tty --volume $(pwd):/code malept/electron-forge-container:latest /bin/bash -c "cd /code && DEBUG=electron-installer-flatpak,flatpak-bundler npm test"
