language: node_js
node_js: 6
dist: xenial
cache:
  npm: true
  directories:
  - $HOME/.local/share/flatpak
services:
- docker
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
  - with-docker

env:
  global:
  - DEBUG: electron-installer-flatpak,flatpak-bundler
matrix:
  include:
  - env: USE_DOCKER=true

before_install: test/ci/before_install.sh

install:
- npm install
- npm update

test: test/ci/test.sh
