language: node_js
node_js: 6
dist: xenial
services:
- docker
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

before_install:
- docker pull malept/electron-forge-container:latest

script:
- sudo docker run --privileged --interactive --tty --volume $(pwd):/code malept/electron-forge-container:latest /bin/bash -c "flatpak install --user --no-deps --assumeyes --arch i386 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-sdk-1.4.flatpakref &&
    flatpak install --user --no-deps --assumeyes --arch i386 --from https://raw.githubusercontent.com/endlessm/flatpak-bundler/master/refs/freedesktop-runtime-1.4.flatpakref &&
    flatpak install --user --no-deps --assumeyes --arch i386 --from https://s3-us-west-2.amazonaws.com/electron-flatpak.endlessm.com/electron-base-app-master.flatpakref &&
    cd /code &&
    DEBUG=electron-installer-flatpak,flatpak-bundler npm test"
