language: node_js
node_js: 6
dist: xenial
cache:
  npm: true
  directories:
  - $HOME/.local/share/flatpak
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
  - with-docker

env:
  global:
  - DEBUG: electron-installer-flatpak,flatpak-bundler
matrix:
  include:
  - env: USE_DOCKER=true
    services:
    - docker
  - env: USE_DOCKER=false

before_install: test/ci/before_install.sh

install:
- npm install
- npm update

script: test/ci/script.sh
